name: End-to-end & units tests

on:
  deployment_status:
jobs:
  tests:
    name: e2e & units tests
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@0609f0983b7a228f052f81ef4c3d6510cae254ad
        with:
          version: 6.10.0
      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
